version: '3.7'

services:
  app:
    build: ./
    depends_on:
      - server
      - db
    ports:
      - 80:8000

  server:
    image: node:12-alpine
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run start"
    working_dir: /server
    volumes:
      - ./packages/server:/server
    environment:
      PGHOST: db
    env_file:
      - .env

  db:
    image: postgres
    volumes:
      - dollar-plan-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}

volumes:
  dollar-plan-db-data:
